### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by haakonnessjoen** [kontakt/Octoprint-Filament-Reloaded#17]
After a lot of fiddling. I relized that you need to restart octoprint for the settings to take effect.

But now I have this problem:

```2017-09-21 18:58:53,753 - octoprint.plugin - ERROR - Error while calling plugin filamentreload
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint-1.3.4.post0.dev0_gfe481e1-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filamentreload/__init__.py", line 61, in on_after_startup
    self._setup_sensor()
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filamentreload/__init__.py", line 53, in _setup_sensor
    GPIO.setmode(GPIO.BCM)
ValueError: A different mode has already been set!
```

**Comment by kontakt** [comment]
Do you have anything else using GPIO pins on your system?
