### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by WVUTampaAlum** [kontakt/Octoprint-Filament-Reloaded#19]
It does not work with bcm or board mode.  Below information is from octoprint.log file.

2017-10-12 14:51:21,127 - octoprint.plugins.filamentreload - INFO - Filament Sensor Reloaded started
2017-10-12 14:51:21,129 - octoprint.plugins.filamentreload - INFO - Setting up sensor.
2017-10-12 14:51:21,133 - octoprint.plugins.filamentreload - INFO - Using BCM Mode
2017-10-12 14:51:21,135 - octoprint.plugins.filamentreload - INFO - Filament Sensor active on GPIO Pin [18]
2017-10-12 14:51:21,138 - octoprint.plugin - ERROR - Error while calling plugin filamentreload
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filamentreload/__init__.py", line 61, in on_after_startup
    self._setup_sensor()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filamentreload/__init__.py", line 55, in _setup_sensor
    GPIO.setup(self.pin, GPIO.IN, pull_up_down=GPIO.PUD_UP)
RuntimeError: No access to /dev/mem.  Try running as root!

**Comment by kontakt** [comment]
I'm not sure what the root of this issue would be, the system should have root already.
